###############################
# DEFAULT 
###############################
enabled: true
developer: false
name: project-site
replicas: 1
image:
    repository: spaceone
    name: project-site
    version: 0.1
imagePullPolicy: IfNotPresent

# Service
#
service:
    type: NodePort
    annotations:
        nil: nil
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
        - name: https
          port: 443
          targetPort: 80
          protocol: TCP

ingress:
    enabled: true
    name: ingress
    annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0 
        alb.ingress.kubernetes.io/scheme: "internet-facing"
        alb.ingress.kubernetes.io/target-type: instance 
        alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:257706363616:certificate/8f002c6f-ba91-4b61-9bf9-0e672cf2d4ff"

endpoint: www.spaceone.org
global:
    namespace: project-site
